adminUser:
  password: vault:pr-202-1abc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-202-1abc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-202-1abc/prow:hmacToken
segmentWriteKey: vault:pr-202-1abc:segmentWriteKey
